"""initial schema

Revision ID: af8c5d07ca88
Revises:
Create Date: 2026-09-01 08:41:13.049607

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af8c5d07ca88'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # PostGIS is required for the geometry columns below (autogenerate does
    # not emit extension statements — add manually).
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('properties',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('property_type', sa.Enum('house', 'apartment', name='property_type'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('commune', sa.Text(), nullable=False),
    sa.Column('surface_in_square_meters', sa.Float(), nullable=True),
    sa.Column('price_in_euros', sa.Float(), nullable=True),
    sa.Column('geometry', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geometry_lambert_93', Geometry(geometry_type='POINT', srid=2154, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('energy_performance_class', sa.Text(), nullable=True),
    sa.Column('greenhouse_gas_class', sa.Text(), nullable=True),
    sa.Column('potential_rent_in_euros', sa.Float(), nullable=True),
    sa.Column('property_tax_in_euros', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_properties'))
    )
    op.create_geospatial_index('idx_properties_geometry', 'properties', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_properties_geometry_lambert_93', 'properties', ['geometry_lambert_93'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_properties_commune'), 'properties', ['commune'], unique=False)
    op.create_index(op.f('ix_properties_energy_performance_class'), 'properties', ['energy_performance_class'], unique=False)
    op.create_index(op.f('ix_properties_greenhouse_gas_class'), 'properties', ['greenhouse_gas_class'], unique=False)
    op.create_index(op.f('ix_properties_potential_rent_in_euros'), 'properties', ['potential_rent_in_euros'], unique=False)
    op.create_index(op.f('ix_properties_price_in_euros'), 'properties', ['price_in_euros'], unique=False)
    op.create_index(op.f('ix_properties_property_tax_in_euros'), 'properties', ['property_tax_in_euros'], unique=False)
    op.create_index(op.f('ix_properties_surface_in_square_meters'), 'properties', ['surface_in_square_meters'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_type', sa.Enum('terrain', 'property', name='score_target_type'), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores'))
    )
    op.create_index(op.f('ix_scores_category'), 'scores', ['category'], unique=False)
    op.create_index(op.f('ix_scores_score'), 'scores', ['score'], unique=False)
    op.create_index(op.f('ix_scores_target_id'), 'scores', ['target_id'], unique=False)
    op.create_geospatial_table('terrains',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('parcel_id', sa.Text(), nullable=False),
    sa.Column('commune', sa.Text(), nullable=False),
    sa.Column('surface_in_square_meters', sa.Float(), nullable=True),
    sa.Column('geometry', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geometry_lambert_93', Geometry(geometry_type='POLYGON', srid=2154, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('zone', sa.Enum('urban', 'periurban', 'rural', name='terrain_zone'), nullable=True),
    sa.Column('buildable', sa.Boolean(), nullable=True),
    sa.Column('estimated_price_in_euros', sa.Float(), nullable=True),
    sa.Column('property_tax_in_euros', sa.Float(), nullable=True),
    sa.Column('slope_in_percent', sa.Float(), nullable=True),
    sa.Column('exposure', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terrains'))
    )
    op.create_geospatial_index('idx_terrains_geometry', 'terrains', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_terrains_geometry_lambert_93', 'terrains', ['geometry_lambert_93'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_terrains_buildable'), 'terrains', ['buildable'], unique=False)
    op.create_index(op.f('ix_terrains_commune'), 'terrains', ['commune'], unique=False)
    op.create_index(op.f('ix_terrains_estimated_price_in_euros'), 'terrains', ['estimated_price_in_euros'], unique=False)
    op.create_index(op.f('ix_terrains_exposure'), 'terrains', ['exposure'], unique=False)
    op.create_index(op.f('ix_terrains_parcel_id'), 'terrains', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_terrains_property_tax_in_euros'), 'terrains', ['property_tax_in_euros'], unique=False)
    op.create_index(op.f('ix_terrains_slope_in_percent'), 'terrains', ['slope_in_percent'], unique=False)
    op.create_index(op.f('ix_terrains_surface_in_square_meters'), 'terrains', ['surface_in_square_meters'], unique=False)
    op.create_index(op.f('ix_terrains_zone'), 'terrains', ['zone'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('account_type', sa.Enum('individual', 'agency', 'notary', name='user_type'), nullable=True),
    sa.Column('siret', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('user', 'moderator', 'admin', name='user_role'), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('locale', sa.String(length=10), server_default='fr', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('tracking_token', sa.Text(), nullable=True),
    sa.Column('feedback_type', sa.Enum('bug', 'idea', 'question', 'complaint', name='feedback_type'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('page', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('new', 'in_progress', 'processed', 'archived', name='feedback_status'), server_default='new', nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedback_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_index(op.f('ix_feedback_tracking_token'), 'feedback', ['tracking_token'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_geospatial_table('listings',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('listing_type', sa.Enum('terrain', 'house', 'apartment', name='listing_type'), nullable=False),
    sa.Column('status', sa.Enum('active', 'under_offer', 'sold', 'rented', 'archived', 'disabled', 'deleted', 'reported', name='listing_status'), server_default='active', nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('commune', sa.Text(), nullable=True),
    sa.Column('geometry', Geometry(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geometry_lambert_93', Geometry(srid=2154, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('price_in_euros', sa.Float(), nullable=True),
    sa.Column('surface_in_square_meters', sa.Float(), nullable=True),
    sa.Column('energy_performance_class', sa.Text(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'import', 'claim', name='listing_source'), server_default='manual', nullable=False),
    sa.Column('claim_status', sa.Enum('none', 'pending', 'approved', 'rejected', name='listing_claim_status'), server_default='none', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_listings_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listings'))
    )
    op.create_geospatial_index('idx_listings_geometry', 'listings', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_listings_geometry_lambert_93', 'listings', ['geometry_lambert_93'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_listings_bedrooms'), 'listings', ['bedrooms'], unique=False)
    op.create_index(op.f('ix_listings_commune'), 'listings', ['commune'], unique=False)
    op.create_index(op.f('ix_listings_energy_performance_class'), 'listings', ['energy_performance_class'], unique=False)
    op.create_index(op.f('ix_listings_owner_id'), 'listings', ['owner_id'], unique=False)
    op.create_index(op.f('ix_listings_price_in_euros'), 'listings', ['price_in_euros'], unique=False)
    op.create_index(op.f('ix_listings_report_count'), 'listings', ['report_count'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_index(op.f('ix_listings_surface_in_square_meters'), 'listings', ['surface_in_square_meters'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sa.Enum('new_offer', 'update', 'listing_status', 'report', 'contact', 'account', 'weekly_digest', name='notification_type'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_geospatial_table('projects',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('project_type', sa.Enum('housing', 'investment', name='project_type'), nullable=False),
    sa.Column('category', sa.Enum('buried-terrain', 'classic-terrain', 'house', 'apartment', name='project_category'), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('zone', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('zone_lambert_93', Geometry(geometry_type='POLYGON', srid=2154, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('zone_center', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('zone_center_lambert_93', Geometry(geometry_type='POINT', srid=2154, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('zone_radius_in_kilometers', sa.Float(), nullable=True),
    sa.Column('max_budget_in_euros', sa.Float(), nullable=True),
    sa.Column('latest_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_offers_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_projects_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_geospatial_index('idx_projects_zone', 'projects', ['zone'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_projects_zone_center', 'projects', ['zone_center'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_projects_zone_center_lambert_93', 'projects', ['zone_center_lambert_93'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_projects_zone_lambert_93', 'projects', ['zone_lambert_93'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_projects_max_budget_in_euros'), 'projects', ['max_budget_in_euros'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('ix_projects_zone_radius_in_kilometers'), 'projects', ['zone_radius_in_kilometers'], unique=False)
    op.create_table('shares',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('share_type', sa.Enum('project', 'comparison', 'map', name='share_type'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shares_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shares'))
    )
    op.create_index(op.f('ix_shares_token'), 'shares', ['token'], unique=True)
    op.create_index(op.f('ix_shares_user_id'), 'shares', ['user_id'], unique=False)
    op.create_table('weighting_profiles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('buried-terrain', 'classic-terrain', 'house', 'apartment', name='profile_category'), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weighting_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weighting_profiles'))
    )
    op.create_index(op.f('ix_weighting_profiles_user_id'), 'weighting_profiles', ['user_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('claim_type', sa.Enum('owner', 'agent', 'agency', 'notary', name='claim_type'), nullable=False),
    sa.Column('proof_document_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='claim_status'), server_default='pending', nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_claims_listing_id_listings')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_claims_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_index(op.f('ix_claims_listing_id'), 'claims', ['listing_id'], unique=False)
    op.create_index(op.f('ix_claims_user_id'), 'claims', ['user_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_contacts_listing_id_listings')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_contacts_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_listing_id'), 'contacts', ['listing_id'], unique=False)
    op.create_index(op.f('ix_contacts_sender_id'), 'contacts', ['sender_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.Enum('terrain', 'property', name='favorite_target_type'), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_favorites_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites'))
    )
    op.create_index(op.f('ix_favorites_project_id'), 'favorites', ['project_id'], unique=False)
    op.create_index(op.f('ix_favorites_target_id'), 'favorites', ['target_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_geospatial_table('priority_zones',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.Enum('high', 'medium', 'low', name='priority_level'), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('geometry_lambert_93', Geometry(geometry_type='POLYGON', srid=2154, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_priority_zones_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priority_zones'))
    )
    op.create_geospatial_index('idx_priority_zones_geometry', 'priority_zones', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_priority_zones_geometry_lambert_93', 'priority_zones', ['geometry_lambert_93'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_priority_zones_project_id'), 'priority_zones', ['project_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('device_fingerprint', sa.Text(), nullable=True),
    sa.Column('report_type', sa.Enum('sold', 'under_offer', 'fraud', 'price_error', 'other', name='report_type'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processed', 'rejected', name='report_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_reports_listing_id_listings')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reports_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_device_fingerprint'), 'reports', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_reports_listing_id'), 'reports', ['listing_id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_listing_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_device_fingerprint'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_priority_zones_project_id'), table_name='priority_zones')
    op.drop_geospatial_index('idx_priority_zones_geometry_lambert_93', table_name='priority_zones', postgresql_using='gist', column_name='geometry_lambert_93')
    op.drop_geospatial_index('idx_priority_zones_geometry', table_name='priority_zones', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('priority_zones')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_target_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_project_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_contacts_sender_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_listing_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_claims_user_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_listing_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_weighting_profiles_user_id'), table_name='weighting_profiles')
    op.drop_table('weighting_profiles')
    op.drop_index(op.f('ix_shares_user_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_token'), table_name='shares')
    op.drop_table('shares')
    op.drop_index(op.f('ix_projects_zone_radius_in_kilometers'), table_name='projects')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_max_budget_in_euros'), table_name='projects')
    op.drop_geospatial_index('idx_projects_zone_lambert_93', table_name='projects', postgresql_using='gist', column_name='zone_lambert_93')
    op.drop_geospatial_index('idx_projects_zone_center_lambert_93', table_name='projects', postgresql_using='gist', column_name='zone_center_lambert_93')
    op.drop_geospatial_index('idx_projects_zone_center', table_name='projects', postgresql_using='gist', column_name='zone_center')
    op.drop_geospatial_index('idx_projects_zone', table_name='projects', postgresql_using='gist', column_name='zone')
    op.drop_geospatial_table('projects')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_listings_surface_in_square_meters'), table_name='listings')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_report_count'), table_name='listings')
    op.drop_index(op.f('ix_listings_price_in_euros'), table_name='listings')
    op.drop_index(op.f('ix_listings_owner_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_energy_performance_class'), table_name='listings')
    op.drop_index(op.f('ix_listings_commune'), table_name='listings')
    op.drop_index(op.f('ix_listings_bedrooms'), table_name='listings')
    op.drop_geospatial_index('idx_listings_geometry_lambert_93', table_name='listings', postgresql_using='gist', column_name='geometry_lambert_93')
    op.drop_geospatial_index('idx_listings_geometry', table_name='listings', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('listings')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_tracking_token'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_terrains_zone'), table_name='terrains')
    op.drop_index(op.f('ix_terrains_surface_in_square_meters'), table_name='terrains')
    op.drop_index(op.f('ix_terrains_slope_in_percent'), table_name='terrains')
    op.drop_index(op.f('ix_terrains_property_tax_in_euros'), table_name='terrains')
    op.drop_index(op.f('ix_terrains_parcel_id'), table_name='terrains')
    op.drop_index(op.f('ix_terrains_exposure'), table_name='terrains')
    op.drop_index(op.f('ix_terrains_estimated_price_in_euros'), table_name='terrains')
    op.drop_index(op.f('ix_terrains_commune'), table_name='terrains')
    op.drop_index(op.f('ix_terrains_buildable'), table_name='terrains')
    op.drop_geospatial_index('idx_terrains_geometry_lambert_93', table_name='terrains', postgresql_using='gist', column_name='geometry_lambert_93')
    op.drop_geospatial_index('idx_terrains_geometry', table_name='terrains', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('terrains')
    op.drop_index(op.f('ix_scores_target_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_score'), table_name='scores')
    op.drop_index(op.f('ix_scores_category'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_properties_surface_in_square_meters'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_tax_in_euros'), table_name='properties')
    op.drop_index(op.f('ix_properties_price_in_euros'), table_name='properties')
    op.drop_index(op.f('ix_properties_potential_rent_in_euros'), table_name='properties')
    op.drop_index(op.f('ix_properties_greenhouse_gas_class'), table_name='properties')
    op.drop_index(op.f('ix_properties_energy_performance_class'), table_name='properties')
    op.drop_index(op.f('ix_properties_commune'), table_name='properties')
    op.drop_geospatial_index('idx_properties_geometry_lambert_93', table_name='properties', postgresql_using='gist', column_name='geometry_lambert_93')
    op.drop_geospatial_index('idx_properties_geometry', table_name='properties', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_table('properties')
    # Native PostgreSQL enum types are not dropped with their tables —
    # remove them explicitly.
    for enum_type in (
        "user_type",
        "user_role",
        "project_type",
        "project_category",
        "profile_category",
        "priority_level",
        "terrain_zone",
        "property_type",
        "score_target_type",
        "listing_type",
        "listing_status",
        "listing_source",
        "listing_claim_status",
        "report_type",
        "report_status",
        "claim_type",
        "claim_status",
        "feedback_type",
        "feedback_status",
        "share_type",
        "notification_type",
        "favorite_target_type",
    ):
        op.execute(f"DROP TYPE {enum_type}")
    # ### end Alembic commands ###
