"""initial schema

Revision ID: e4f7812cece6
Revises:
Create Date: 2026-09-01 01:33:21.255247

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e4f7812cece6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # PostGIS is required for the geometry columns below.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "biens",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("type", sa.Enum("maison", "appartement", name="bien_type"), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("commune", sa.Text(), nullable=False),
        sa.Column("surface_m2", sa.Float(), nullable=True),
        sa.Column("price_eur", sa.Float(), nullable=True),
        sa.Column(
            "geometry",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "geometry_2154",
            Geometry(
                geometry_type="POINT",
                srid=2154,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("dpe", sa.Text(), nullable=True),
        sa.Column("ges", sa.Text(), nullable=True),
        sa.Column("loyer_potentiel_eur", sa.Float(), nullable=True),
        sa.Column("taxe_fonciere_eur", sa.Float(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_biens")),
    )
    op.create_index(op.f("ix_biens_commune"), "biens", ["commune"], unique=False)
    op.create_index(op.f("ix_biens_dpe"), "biens", ["dpe"], unique=False)
    op.create_index(op.f("ix_biens_ges"), "biens", ["ges"], unique=False)
    op.create_index(
        op.f("ix_biens_loyer_potentiel_eur"), "biens", ["loyer_potentiel_eur"], unique=False
    )
    op.create_index(op.f("ix_biens_price_eur"), "biens", ["price_eur"], unique=False)
    op.create_index(op.f("ix_biens_surface_m2"), "biens", ["surface_m2"], unique=False)
    op.create_index(
        op.f("ix_biens_taxe_fonciere_eur"), "biens", ["taxe_fonciere_eur"], unique=False
    )
    op.create_table(
        "scores",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "target_type", sa.Enum("terrain", "bien", name="score_target_type"), nullable=False
        ),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scores")),
    )
    op.create_index(op.f("ix_scores_category"), "scores", ["category"], unique=False)
    op.create_index(op.f("ix_scores_score"), "scores", ["score"], unique=False)
    op.create_index(op.f("ix_scores_target_id"), "scores", ["target_id"], unique=False)
    op.create_table(
        "terrains",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("parcelle_id", sa.Text(), nullable=False),
        sa.Column("commune", sa.Text(), nullable=False),
        sa.Column("surface_m2", sa.Float(), nullable=True),
        sa.Column(
            "geometry",
            Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "geometry_2154",
            Geometry(
                geometry_type="POLYGON",
                srid=2154,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "zone", sa.Enum("urbain", "periurbain", "rural", name="terrain_zone"), nullable=True
        ),
        sa.Column("buildable", sa.Boolean(), nullable=True),
        sa.Column("estimated_price_eur", sa.Float(), nullable=True),
        sa.Column("taxe_fonciere_eur", sa.Float(), nullable=True),
        sa.Column("slope_pct", sa.Float(), nullable=True),
        sa.Column("exposure", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_terrains")),
    )
    op.create_index(op.f("ix_terrains_buildable"), "terrains", ["buildable"], unique=False)
    op.create_index(op.f("ix_terrains_commune"), "terrains", ["commune"], unique=False)
    op.create_index(
        op.f("ix_terrains_estimated_price_eur"), "terrains", ["estimated_price_eur"], unique=False
    )
    op.create_index(op.f("ix_terrains_exposure"), "terrains", ["exposure"], unique=False)
    op.create_index(op.f("ix_terrains_parcelle_id"), "terrains", ["parcelle_id"], unique=False)
    op.create_index(op.f("ix_terrains_slope_pct"), "terrains", ["slope_pct"], unique=False)
    op.create_index(op.f("ix_terrains_surface_m2"), "terrains", ["surface_m2"], unique=False)
    op.create_index(
        op.f("ix_terrains_taxe_fonciere_eur"), "terrains", ["taxe_fonciere_eur"], unique=False
    )
    op.create_index(op.f("ix_terrains_zone"), "terrains", ["zone"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("nom", sa.Text(), nullable=True),
        sa.Column("prenom", sa.Text(), nullable=True),
        sa.Column(
            "type", sa.Enum("particulier", "agence", "notaire", name="user_type"), nullable=True
        ),
        sa.Column("siret", sa.Text(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("user", "moderateur", "admin", name="user_role"),
            server_default="user",
            nullable=False,
        ),
        sa.Column("bloque", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("email_verifie", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("score_fiabilite", sa.Float(), nullable=True),
        sa.Column("locale", sa.String(length=10), server_default="fr", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "annonces",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type", sa.Enum("terrain", "maison", "appartement", name="annonce_type"), nullable=False
        ),
        sa.Column(
            "statut",
            sa.Enum(
                "active",
                "sous_offre",
                "vendu",
                "loué",
                "archivée",
                "désactivée",
                "supprimée",
                "signalée",
                name="annonce_statut",
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("commune", sa.Text(), nullable=True),
        sa.Column(
            "geometry",
            Geometry(srid=4326, dimension=2, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column(
            "geometry_2154",
            Geometry(srid=2154, dimension=2, from_text="ST_GeomFromEWKT", name="geometry"),
            nullable=True,
        ),
        sa.Column("price_eur", sa.Float(), nullable=True),
        sa.Column("surface_m2", sa.Float(), nullable=True),
        sa.Column("dpe", sa.Text(), nullable=True),
        sa.Column("chambres", sa.Integer(), nullable=True),
        sa.Column("photos", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("caracteristiques", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("manuel", "import", "claim", name="annonce_source"),
            server_default="manuel",
            nullable=False,
        ),
        sa.Column(
            "claim_status",
            sa.Enum("none", "pending", "approved", "rejected", name="annonce_claim_status"),
            server_default="none",
            nullable=False,
        ),
        sa.Column(
            "date_depot",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "date_mise_a_jour",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("date_derniere_verification", sa.DateTime(timezone=True), nullable=True),
        sa.Column("nombre_signalements", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_annonces_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_annonces")),
    )
    op.create_index(op.f("ix_annonces_chambres"), "annonces", ["chambres"], unique=False)
    op.create_index(op.f("ix_annonces_commune"), "annonces", ["commune"], unique=False)
    op.create_index(op.f("ix_annonces_dpe"), "annonces", ["dpe"], unique=False)
    op.create_index(
        op.f("ix_annonces_nombre_signalements"), "annonces", ["nombre_signalements"], unique=False
    )
    op.create_index(op.f("ix_annonces_owner_id"), "annonces", ["owner_id"], unique=False)
    op.create_index(op.f("ix_annonces_price_eur"), "annonces", ["price_eur"], unique=False)
    op.create_index(op.f("ix_annonces_statut"), "annonces", ["statut"], unique=False)
    op.create_index(op.f("ix_annonces_surface_m2"), "annonces", ["surface_m2"], unique=False)
    op.create_table(
        "feedback",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("token_suivi", sa.Text(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("bug", "idee", "question", "doléance", name="feedback_type"),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("page", sa.Text(), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("nouveau", "en_cours", "traite", "archive", name="feedback_status"),
            server_default="nouveau",
            nullable=False,
        ),
        sa.Column("reponse", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_feedback_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
    )
    op.create_index(op.f("ix_feedback_token_suivi"), "feedback", ["token_suivi"], unique=False)
    op.create_index(op.f("ix_feedback_user_id"), "feedback", ["user_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "nouvelle_offre",
                "mise_a_jour",
                "annonce_statut",
                "signalement",
                "contact",
                "compte",
                "recap_hebdo",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("titre", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("lien", sa.Text(), nullable=True),
        sa.Column("lu", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "partages",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column(
            "type", sa.Enum("projet", "compare", "carte", name="partage_type"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_partages_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partages")),
    )
    op.create_index(op.f("ix_partages_token"), "partages", ["token"], unique=True)
    op.create_index(op.f("ix_partages_user_id"), "partages", ["user_id"], unique=False)
    op.create_table(
        "profils_ponderation",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("nom", sa.Text(), nullable=False),
        sa.Column(
            "categorie",
            sa.Enum(
                "terrain-terre",
                "terrain-classique",
                "maison",
                "appartement",
                name="profil_categorie",
            ),
            nullable=False,
        ),
        sa.Column("poids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_profils_ponderation_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profils_ponderation")),
    )
    op.create_index(
        op.f("ix_profils_ponderation_user_id"), "profils_ponderation", ["user_id"], unique=False
    )
    op.create_table(
        "projets",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("nom", sa.Text(), nullable=False),
        sa.Column(
            "type", sa.Enum("logement", "investissement", name="projet_type"), nullable=False
        ),
        sa.Column(
            "categorie",
            sa.Enum(
                "terrain-terre",
                "terrain-classique",
                "maison",
                "appartement",
                name="projet_categorie",
            ),
            nullable=False,
        ),
        sa.Column("criteres", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "zone",
            Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "zone_2154",
            Geometry(
                geometry_type="POLYGON",
                srid=2154,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "zone_centre",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "zone_centre_2154",
            Geometry(
                geometry_type="POINT",
                srid=2154,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("zone_rayon_km", sa.Float(), nullable=True),
        sa.Column("budget_max", sa.Float(), nullable=True),
        sa.Column("derniers_resultats", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("nouvelles_offres", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "date_creation",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("date_derniere_consultation", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "date_mise_a_jour",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_projets_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projets")),
    )
    op.create_index(op.f("ix_projets_budget_max"), "projets", ["budget_max"], unique=False)
    op.create_index(op.f("ix_projets_user_id"), "projets", ["user_id"], unique=False)
    op.create_index(op.f("ix_projets_zone_rayon_km"), "projets", ["zone_rayon_km"], unique=False)
    op.create_table(
        "claims",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("annonce_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("proprietaire", "mandataire", "agence", "notaire", name="claim_type"),
            nullable=False,
        ),
        sa.Column("justificatif_url", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", name="claim_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("note_admin", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["annonce_id"], ["annonces.id"], name=op.f("fk_claims_annonce_id_annonces")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_claims_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claims")),
    )
    op.create_index(op.f("ix_claims_annonce_id"), "claims", ["annonce_id"], unique=False)
    op.create_index(op.f("ix_claims_user_id"), "claims", ["user_id"], unique=False)
    op.create_table(
        "contacts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("annonce_id", sa.Uuid(), nullable=False),
        sa.Column("contacteur_id", sa.Uuid(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("lu", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["annonce_id"], ["annonces.id"], name=op.f("fk_contacts_annonce_id_annonces")
        ),
        sa.ForeignKeyConstraint(
            ["contacteur_id"], ["users.id"], name=op.f("fk_contacts_contacteur_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
    )
    op.create_index(op.f("ix_contacts_annonce_id"), "contacts", ["annonce_id"], unique=False)
    op.create_index(op.f("ix_contacts_contacteur_id"), "contacts", ["contacteur_id"], unique=False)
    op.create_table(
        "favoris",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "target_type", sa.Enum("terrain", "bien", name="favori_target_type"), nullable=False
        ),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("projet_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["projet_id"], ["projets.id"], name=op.f("fk_favoris_projet_id_projets")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_favoris_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_favoris")),
    )
    op.create_index(op.f("ix_favoris_projet_id"), "favoris", ["projet_id"], unique=False)
    op.create_index(op.f("ix_favoris_target_id"), "favoris", ["target_id"], unique=False)
    op.create_index(op.f("ix_favoris_user_id"), "favoris", ["user_id"], unique=False)
    op.create_table(
        "signalements",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("annonce_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("device_fingerprint", sa.Text(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("vendu", "sous_offre", "faux", "erreur_prix", "autre", name="signalement_type"),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "statut",
            sa.Enum("en_attente", "traite", "rejeté", name="signalement_statut"),
            server_default="en_attente",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["annonce_id"], ["annonces.id"], name=op.f("fk_signalements_annonce_id_annonces")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_signalements_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signalements")),
    )
    op.create_index(
        op.f("ix_signalements_annonce_id"), "signalements", ["annonce_id"], unique=False
    )
    op.create_index(
        op.f("ix_signalements_device_fingerprint"),
        "signalements",
        ["device_fingerprint"],
        unique=False,
    )
    op.create_index(op.f("ix_signalements_user_id"), "signalements", ["user_id"], unique=False)
    op.create_table(
        "zones_priorite",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("projet_id", sa.Uuid(), nullable=False),
        sa.Column(
            "niveau",
            sa.Enum("haute", "moyenne", "basse", name="zone_priorite_niveau"),
            nullable=False,
        ),
        sa.Column(
            "geometry",
            Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "geometry_2154",
            Geometry(
                geometry_type="POLYGON",
                srid=2154,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["projet_id"], ["projets.id"], name=op.f("fk_zones_priorite_projet_id_projets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zones_priorite")),
    )
    op.create_index(
        op.f("ix_zones_priorite_projet_id"), "zones_priorite", ["projet_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_zones_priorite_projet_id"), table_name="zones_priorite")
    op.drop_table("zones_priorite")
    op.drop_index(op.f("ix_signalements_user_id"), table_name="signalements")
    op.drop_index(op.f("ix_signalements_device_fingerprint"), table_name="signalements")
    op.drop_index(op.f("ix_signalements_annonce_id"), table_name="signalements")
    op.drop_table("signalements")
    op.drop_index(op.f("ix_favoris_user_id"), table_name="favoris")
    op.drop_index(op.f("ix_favoris_target_id"), table_name="favoris")
    op.drop_index(op.f("ix_favoris_projet_id"), table_name="favoris")
    op.drop_table("favoris")
    op.drop_index(op.f("ix_contacts_contacteur_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_annonce_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_claims_user_id"), table_name="claims")
    op.drop_index(op.f("ix_claims_annonce_id"), table_name="claims")
    op.drop_table("claims")
    op.drop_index(op.f("ix_projets_zone_rayon_km"), table_name="projets")
    op.drop_index(op.f("ix_projets_user_id"), table_name="projets")
    op.drop_index(op.f("ix_projets_budget_max"), table_name="projets")
    op.drop_table("projets")
    op.drop_index(op.f("ix_profils_ponderation_user_id"), table_name="profils_ponderation")
    op.drop_table("profils_ponderation")
    op.drop_index(op.f("ix_partages_user_id"), table_name="partages")
    op.drop_index(op.f("ix_partages_token"), table_name="partages")
    op.drop_table("partages")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_feedback_user_id"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_token_suivi"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_index(op.f("ix_annonces_surface_m2"), table_name="annonces")
    op.drop_index(op.f("ix_annonces_statut"), table_name="annonces")
    op.drop_index(op.f("ix_annonces_price_eur"), table_name="annonces")
    op.drop_index(op.f("ix_annonces_owner_id"), table_name="annonces")
    op.drop_index(op.f("ix_annonces_nombre_signalements"), table_name="annonces")
    op.drop_index(op.f("ix_annonces_dpe"), table_name="annonces")
    op.drop_index(op.f("ix_annonces_commune"), table_name="annonces")
    op.drop_index(op.f("ix_annonces_chambres"), table_name="annonces")
    op.drop_table("annonces")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_terrains_zone"), table_name="terrains")
    op.drop_index(op.f("ix_terrains_taxe_fonciere_eur"), table_name="terrains")
    op.drop_index(op.f("ix_terrains_surface_m2"), table_name="terrains")
    op.drop_index(op.f("ix_terrains_slope_pct"), table_name="terrains")
    op.drop_index(op.f("ix_terrains_parcelle_id"), table_name="terrains")
    op.drop_index(op.f("ix_terrains_exposure"), table_name="terrains")
    op.drop_index(op.f("ix_terrains_estimated_price_eur"), table_name="terrains")
    op.drop_index(op.f("ix_terrains_commune"), table_name="terrains")
    op.drop_index(op.f("ix_terrains_buildable"), table_name="terrains")
    op.drop_table("terrains")
    op.drop_index(op.f("ix_scores_target_id"), table_name="scores")
    op.drop_index(op.f("ix_scores_score"), table_name="scores")
    op.drop_index(op.f("ix_scores_category"), table_name="scores")
    op.drop_table("scores")
    op.drop_index(op.f("ix_biens_taxe_fonciere_eur"), table_name="biens")
    op.drop_index(op.f("ix_biens_surface_m2"), table_name="biens")
    op.drop_index(op.f("ix_biens_price_eur"), table_name="biens")
    op.drop_index(op.f("ix_biens_loyer_potentiel_eur"), table_name="biens")
    op.drop_index(op.f("ix_biens_ges"), table_name="biens")
    op.drop_index(op.f("ix_biens_dpe"), table_name="biens")
    op.drop_index(op.f("ix_biens_commune"), table_name="biens")
    op.drop_table("biens")
    # Native enum types are not dropped with their tables — drop them explicitly
    # so the migration is fully reversible.
    for enum_type in [
        "bien_type",
        "score_target_type",
        "terrain_zone",
        "user_type",
        "user_role",
        "annonce_type",
        "annonce_statut",
        "annonce_source",
        "annonce_claim_status",
        "feedback_type",
        "feedback_status",
        "notification_type",
        "partage_type",
        "profil_categorie",
        "projet_type",
        "projet_categorie",
        "claim_type",
        "claim_status",
        "favori_target_type",
        "signalement_type",
        "signalement_statut",
        "zone_priorite_niveau",
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_type}")
    # ### end Alembic commands ###
