name: PR meta

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-meta:
    uses: ostara-labs/devtools/.github/workflows/pr-meta.yml@ea7b224467989b6ab87e8166f1bb4d07ab198a7d # v1.9.0
